<a href="https://colab.research.google.com/github/modemmahesh/iris_flower_classificartion/blob/main/iris_classification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Importing the required modules
==

In [ ]:
import numpy as np
import pandas as pd



Loading the Iris dataset from sklearn
==
sklearn library contains some inbuit datasets.
  Among those iris is also one of the dataset that contains 150 rows and 4 features.

In [ ]:
from sklearn.datasets import load_iris
iris=load_iris()

Loading the dataset
==

In [ ]:
iris

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

loading the features of the data
==

In [ ]:
dir(iris)

['DESCR',
 'data',
 'data_module',
 'feature_names',
 'filename',
 'frame',
 'target',
 'target_names']

Getting no. of rows
==

In [ ]:
iris.data.size

600

Extracting the indepedent variables
==


In [ ]:
iris.data
iris.columns

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

Getting the target values
==


In [ ]:
iris.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

Getting the target names 
==

In [ ]:
iris.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

Number of features
==

In [ ]:
iris.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

splitting the data for training and testing
==

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(iris.data,iris.target,test_size=0.2,random_state=1)

size of the training data
==

In [ ]:
x_train.size

480

size of the testing data
==

In [ ]:
x_test.size

120

making the model
==

In [ ]:
from sklearn.svm import SVC
svm=SVC()

fitting the training data
==

In [ ]:
svm.fit(x_train,y_train)

SVC()

testing the model
==


In [ ]:
y_pred=svm.predict(x_test)

accuracy of the model
==

In [ ]:
from sklearn.metrics import confusion_matrix,accuracy_score
cm=confusion_matrix(y_test,y_pred)
acc=accuracy_score(y_test,y_pred)
print("Confusion matrix is \n",cm)
print("Accuracy of the model is ",acc*100)

Confusion matrix is 
 [[11  0  0]
 [ 0 12  1]
 [ 0  0  6]]
Accuracy of the model is  96.66666666666667


Deploying the model
====

In [ ]:
def guess(x):
    b=svm.predict([x])
    if b[0]==0:
        print("The flower is Setosa \n")
    elif b[0]==1:
        print("The flower is Versi color \n")
    elif b[0]==2:
        print("The flower is Verginica \n")
        
        
while True:
    print("enter 1. to predict the flower \n enter 2. to exit")
    y=int(input(""))
    if y==1:
        a=float(input("enter sepal length (cm)"))
        b=float(input("enter sepal width (cm)"))
        c=float(input("enter petal length (cm)"))
        d=float(input("enterpetal width (cm) "))
        print("\n")
        x=[a,b,c,d]
        guess(x)
    elif y==2:
        break
    else:
        print("enter correct input")

enter 1. to predict the flower 
 enter 2. to exit
1
enter sepal length (cm)1.2
enter sepal width (cm)2.2
enter petal length (cm)2.5
enterpetal width (cm) 3.8


The flower is Verginica 

enter 1. to predict the flower 
 enter 2. to exit
2
